class TestData:
    URL = 'https://connect.sandbox.appetize-dev.com/login'
    USERNAME = 'qaregressionteam'
    PWD = '@ppetiz3!'
    PHRASE = 'Login'
    VENUE = '393'
    NAME_ITEM = 'autogiuli'
    COST_ITEM = '11'
    TYPE_ITEM = 'drink'
    TITLE = 'Appetize Connect - Login'
    TITLE1 = 'Appetize Connect - Login'
